name: "Build And Publish Backend to GHCR"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build (dev or main)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - main

concurrency:
  group: Backend
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      should_push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
      image_tag: ${{ steps.meta.outputs.tags }}
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          repository: buenosdiasn/PTL-be
          fetch-depth: 1
          token: ${{ secrets.GHA_PAT }}
          ref: ${{ github.event.inputs.branch || github.ref_name }}

      - name: Debug Secret
        run: echo "Token length is ${{ secrets.GHA_PAT | length }}"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine environment
        id: env
        run: |
          # Use the selected branch from workflow_dispatch or the current branch
          BRANCH="${{ github.event.inputs.branch || github.ref_name }}"
          if [[ "$BRANCH" == "main" ]]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT

      - name: Log in to GitHub Container Registry
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.PACTOR}}
          password: ${{ secrets.REGISTRY_PAT }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ptl-backend
          tags: |
            type=ref,event=branch,suffix=-{{date 'YYYYMMDD'}}-{{sha}}
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=${{ steps.env.outputs.environment }}-latest
            type=raw,value=${{ steps.env.outputs.branch_name }}-latest
            type=raw,value=${{ steps.env.outputs.branch_name }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
